export const USER_PENDING = "USER_PENDING";
export const USER_FULFILLED = "USER_FULFILLED";
export const USER_REJECTED = "USER_REJECTED";
export const USER_EDIT_PENDING = "USER_EDIT_PENDING";
export const USER_EDIT_FULFILLED = "USER_EDIT_FULFILLED";
export const USER_EDIT_REJECTED = "USER_EDIT_REJECTED";